$ThemeSlug = 'painmed'
$RemoteUser = 'orlove'
$RemoteHost = 'orlove.beget.tech'
$RemoteThemeDir = 'painmed.orlove.beget.tech/public_html/wp-content/themes/painmed'
$RemoteBackupBaseDir = '_theme_backups/painmed'
